# Here is the original
# https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
template:
  spec:
    containers:
      - name: runner
        image: "ghcr.io/chair-of-software-engineering-magdeburg/action-runner/action-runner:latest"
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
